In [39]:
%load_ext autoreload
%autoreload 2

import pandas as pd

from gdynia_srodmiescie.loading import load_short, load_long
from gdynia_srodmiescie import building_features as bf
from gdynia_srodmiescie import street_metrics as sm
from gdynia_srodmiescie import styling as st

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [40]:
short = load_short("../../data/processed/fixed/srodmiescie.csv")
long = load_long("../../data/processed/fixed/srodmiescie_long_categories.csv")
buildings = (
    short.pipe(bf.add_building_floor_flags, long)
    .pipe(bf.add_building_type)
    .pipe(bf.add_building_periods)
    .pipe(bf.add_vacancy_kind, long)
)

crosstab street x category

In [41]:
pd.crosstab(
    long.reset_index()["addr_street"],
    long.reset_index()["category"],
    normalize="columns",
).pipe(st.background_gradient, axis="index").pipe(st.percent_formatter)

crosstab time period x type of building

In [42]:
pd.crosstab(
    buildings.reset_index()["time_period"],
    buildings.reset_index()["type"],
    normalize="columns",
).pipe(st.background_gradient, axis="index").pipe(st.percent_formatter)

In [43]:
columns_for_corr_1 = [
    "num_premises_wo_vacant",
    "func_entropy",
    "share_vacant",
    "share_mix_use",
    "leader_share",
]
street_metr = long.pipe(sm.street_metrics, buildings)
street_metr.loc[:, columns_for_corr_1].corr(method="spearman")

,num_premises_wo_vacant,func_entropy,share_vacant,share_mix_use,leader_share
num_premises_wo_vacant,1.000000,0.304932,0.479918,0.124520,0.053353
func_entropy,0.304932,1.000000,-0.056164,0.215579,-0.771613
share_vacant,0.479918,-0.056164,1.000000,-0.023287,0.177264
share_mix_use,0.124520,0.215579,-0.023287,1.000000,-0.247426
leader_share,0.053353,-0.771613,0.177264,-0.247426,1.000000

In [44]:
columns_for_corr_2 = [
    "num_premises_wo_vacant",
    "func_entropy",
]
street_metr.loc[lambda d: d.index != "Świętojańska", columns_for_corr_2].corr(
    method="pearson"
)

                        num_premises_wo_vacant  func_entropy
num_premises_wo_vacant                1.000000      0.302331
func_entropy                          0.302331      1.000000

In [45]:
street_metr.loc[:, columns_for_corr_2].corr(method="pearson")

                        num_premises_wo_vacant  func_entropy
num_premises_wo_vacant                1.000000      0.095844
func_entropy                          0.095844      1.000000

before vs after

In [46]:
old_ids = short.loc[
    lambda e: e["date_of_checking"] < pd.to_datetime("2026-10-22")
].index

old_long = long.loc[lambda d: d.index.isin(old_ids)]
old_buildings = buildings.loc[lambda d: d.index.isin(old_ids)]

street_metr_old = old_long.pipe(sm.street_metrics, old_buildings)

func_entropy_before_after = pd.concat(
    {
        "after": street_metr.loc[:, columns_for_corr_2].assign(
            rank_after=lambda d: d["func_entropy"].rank(method="dense", ascending=False)
        ),
        "before": street_metr_old.loc[:, columns_for_corr_2].assign(
            rank_before=lambda d: d["func_entropy"].rank(
                method="dense", ascending=False
            )
        ),
    },
    axis=1,
)


func_entropy_before_after.dropna().sort_values(("after", "rank_after")).loc[
    :, ("before", ["num_premises_wo_vacant", "func_entropy"])
].corr(method="spearman")

                        num_premises_wo_vacant  func_entropy
num_premises_wo_vacant                1.000000      0.329968
func_entropy                          0.329968      1.000000

In [47]:
func_entropy_before_after.dropna().sort_values(("after", "rank_after")).loc[
    :, ("after", ["num_premises_wo_vacant", "func_entropy"])
].corr(method="spearman")

                        num_premises_wo_vacant  func_entropy
num_premises_wo_vacant                1.000000      0.307219
func_entropy                          0.307219      1.000000

In [48]:
func_entropy_before_after.dropna().sort_values(("after", "rank_after")).loc[
    :, [("after", "func_entropy"), ("before", "func_entropy")]
].corr(method="spearman")

                           after       before
                    func_entropy func_entropy
after  func_entropy      1.00000      0.98906
before func_entropy      0.98906      1.00000

Num of all share how much of all premises are in mixed-use buildings

In [49]:
func_ground_floor = ["mixed-use", "service"]

ground_profiles = long.pipe(sm.ground_floor_profile, buildings)
ground_profiles.loc[:, func_ground_floor].pipe(
    st.background_gradient, axis="columns"
).pipe(st.percent_formatter)

vacancy vs building condition

In [50]:
pd.crosstab(buildings["condition"], buildings["is_vacant"], normalize="index").pipe(
    st.background_gradient
).pipe(st.percent_formatter)

vacancy kind vs building condition

In [51]:
pd.crosstab(buildings["condition"], buildings["vacancy_kind"], normalize="index").pipe(
    st.background_gradient
).pipe(st.percent_formatter)

vacancy kind vs time period

In [52]:
pd.crosstab(
    buildings["vacancy_kind"], buildings["time_period"], normalize="columns"
).pipe(st.background_gradient).pipe(st.percent_formatter)

streets with vacancy among working

In [53]:
pd.crosstab(
    buildings["addr_street"],
    buildings["vacancy_kind"].eq("vacant among working"),
    normalize="index",
).rename(columns={False: "no vacant among working", True: "vacant among working"}).join(
    pd.crosstab(
        buildings["addr_street"],
        buildings["vacancy_kind"].eq("vacant among working"),
        margins=True,
    ).rename(columns={"All": "sum_build_per_street"})["sum_build_per_street"]
).loc[lambda d: d["vacant among working"].gt(0)].pipe(
    st.background_gradient, subset="vacant among working"
).pipe(st.percent_formatter, subset=["no vacant among working", "vacant among working"])

corr type entropy x func entropy

In [54]:
types_for_corr_3 = ["type_entropy", "func_entropy", "num_premises_wo_vacant"]

building_type_shares = buildings.pipe(sm.building_type_shares)
type_entropy = building_type_shares.pipe(sm.entropy_from_shares)
street_metr_type_entropy = street_metr.join(type_entropy)
street_metr_type_entropy.loc[:, types_for_corr_3].corr(method="spearman")

                        type_entropy  func_entropy  num_premises_wo_vacant
type_entropy                1.000000      0.562671               -0.004110
func_entropy                0.562671      1.000000                0.304932
num_premises_wo_vacant     -0.004110      0.304932                1.000000

In [55]:
building_type_shares.join(type_entropy["type_entropy"]).loc[
    street_metr.index
].sort_values("type_entropy", ascending=False).pipe(
    st.background_gradient, subset=building_type_shares.columns
).pipe(st.percent_formatter, subset=building_type_shares.columns).pipe(
    st.decimal_formatter, decimals=3, subset="type_entropy"
)

In [ ]:
street_metr_type_entropy.sort_values("func_entropy", ascending=False).iloc[2:].loc[
    :, ["func_entropy", "type_entropy"]
].corr(method="spearman")

              func_entropy  type_entropy
func_entropy      1.000000      0.460513
type_entropy      0.460513      1.000000

In [57]:
long.pipe(sm.street_metrics, buildings, cat_omitted=bf.NON_SERVICE).join(
    type_entropy
).loc[:, ["func_entropy", "type_entropy"]].corr(method="spearman")

              func_entropy  type_entropy
func_entropy      1.000000      0.365627
type_entropy      0.365627      1.000000