In [1]:
import pandas as pd
import numpy as np

column_types = {
    "id": "Int64",
    "osm_id": "str",
    "addr_street": "str",
    "addr_number": "str",
    "ground_floor_group": "str",
    "ground_floor_function": "str",
    "upper_floor_group": "str",
    "upper_floor_function": "str",
    "number_of_storeys": "Int64",
    "is_mixed_use": "boolean",
    "build_year_est": "Int64",
    "arch_style": "str",
    "condition": "Int64",
    "max_height": "float64",
    "is_heritage": "str",
    "source": "str",
    "confidence": "Int64",
    "date_of_checking": "str",
}

In [2]:
data_gdynia = pd.read_csv(
    "../data/raw/srodmiescie_raw.csv", sep=";", index_col=0, dtype=column_types
).dropna(subset="ground_floor_function")

data_gdynia.head()

,osm_id,addr_street,addr_number,ground_floor_group,ground_floor_function,upper_floor_group,upper_floor_function,number_of_storeys,is_mixed_use,build_year_est,arch_style,condition,max_height,is_heritage,source,confidence,date_of_checking
id,,,,,,,,,,,,,,,,,
1,127184291,Świętego Piotra,8,NaN,Hotel,NaN,Hotel,7,<NA>,2000,Współczesność,3,NaN,NaN,google.com/maps,3,27.09.2026
2,890729731,Świętego Piotra,6D,NaN,Mieszkaniowa Wielorodzinna,NaN,Mieszkaniowa Wielorodzinna,5,<NA>,2020,Współczesność,3,NaN,NaN,google.com/maps,3,27.09.2026
3,890292040,Węglowa,22,NaN,Centrum Handlowe,NaN,Mieszkaniowa Wielorodzinna,17,<NA>,2020,Współczesność,3,NaN,NaN,google.com/maps,3,27.09.2026
4,890729732,Świętego Piotra,6,NaN,Mieszkaniowa Wielorodzinna,NaN,Mieszkaniowa Wielorodzinna,17,<NA>,2020,Współczesność,3,NaN,NaN,google.com/maps,3,27.09.2026
5,136885205,Tadeusza Wendy,15,NaN,Centrum Medyczne,NaN,Centrum Medyczne,6,<NA>,2000,Współczesność,3,NaN,NaN,google.com/maps,2,27.09.2026

1.

In [ ]:
group = data_gdynia.groupby("addr_street")
group.ngroups
group.get_group("Świętego Piotra").head(3)

,osm_id,addr_street,addr_number,ground_floor_group,ground_floor_function,upper_floor_group,upper_floor_function,number_of_storeys,is_mixed_use,build_year_est,arch_style,condition,max_height,is_heritage,source,confidence,date_of_checking
id,,,,,,,,,,,,,,,,,
1,127184291,Świętego Piotra,8,NaN,Hotel,NaN,Hotel,7,<NA>,2000,Współczesność,3,NaN,NaN,google.com/maps,3,27.09.2026
2,890729731,Świętego Piotra,6D,NaN,Mieszkaniowa Wielorodzinna,NaN,Mieszkaniowa Wielorodzinna,5,<NA>,2020,Współczesność,3,NaN,NaN,google.com/maps,3,27.09.2026
4,890729732,Świętego Piotra,6,NaN,Mieszkaniowa Wielorodzinna,NaN,Mieszkaniowa Wielorodzinna,17,<NA>,2020,Współczesność,3,NaN,NaN,google.com/maps,3,27.09.2026

In [ ]:
assert group.ngroups == data_gdynia["addr_street"].nunique()

2.

In [ ]:
count = data_gdynia.groupby("addr_street")["addr_number"].agg("count")
size = data_gdynia.groupby("addr_street")["addr_number"].agg("size")
diff = count - size
diff[diff != 0].head(5)

addr_street
3 Maja                     -2
Antoniego Abrahama         -1
Antoniego Hryniewickiego   -1
Armii Krajowej             -1
Hilarego Jastaka           -1
Name: addr_number, dtype: int64

In [ ]:
a = data_gdynia["addr_street"].value_counts().rename("addr_number").sort_index()
b = (
    data_gdynia.groupby("addr_street")["addr_number"]
    .agg("size")
    .sort_values(ascending=False)
    .sort_index()
)

assert a.equals(b)

3.

In [ ]:
data_gdynia.groupby(["addr_street", "condition"])["osm_id"].count().unstack().head()

condition                              1     2     3   4
addr_street
10 Lutego                            1.0  24.0  23.0 NaN
3 Maja                               NaN  16.0  10.0 NaN
Aleja Jana Pawła II                  NaN   9.0   6.0 NaN
Aleja Marszałka Józefa Piłsudskiego  NaN   2.0   1.0 NaN
Antoniego Abrahama                   2.0  66.0  12.0 NaN

4.

In [ ]:
data_gdynia.groupby("addr_street")["condition"].agg(
    ["min", "max", "mean", "median"]
).head()

                                     min  max      mean  median
addr_street
10 Lutego                              1    3  2.458333     2.0
3 Maja                                 2    3  2.384615     2.0
Aleja Jana Pawła II                    2    3       2.4     2.0
Aleja Marszałka Józefa Piłsudskiego    2    3  2.333333     2.0
Antoniego Abrahama                     1    3     2.125     2.0

5.

In [ ]:
data_gdynia = data_gdynia.assign(
    nfunc=lambda d: d["ground_floor_function"].str.count(",") + 1
)
data_gdynia.head()

,osm_id,addr_street,addr_number,ground_floor_group,ground_floor_function,upper_floor_group,upper_floor_function,number_of_storeys,is_mixed_use,build_year_est,arch_style,condition,max_height,is_heritage,source,confidence,date_of_checking,nfunc
id,,,,,,,,,,,,,,,,,,
1,127184291,Świętego Piotra,8,NaN,Hotel,NaN,Hotel,7,<NA>,2000,Współczesność,3,NaN,NaN,google.com/maps,3,27.09.2026,1
2,890729731,Świętego Piotra,6D,NaN,Mieszkaniowa Wielorodzinna,NaN,Mieszkaniowa Wielorodzinna,5,<NA>,2020,Współczesność,3,NaN,NaN,google.com/maps,3,27.09.2026,1
3,890292040,Węglowa,22,NaN,Centrum Handlowe,NaN,Mieszkaniowa Wielorodzinna,17,<NA>,2020,Współczesność,3,NaN,NaN,google.com/maps,3,27.09.2026,1
4,890729732,Świętego Piotra,6,NaN,Mieszkaniowa Wielorodzinna,NaN,Mieszkaniowa Wielorodzinna,17,<NA>,2020,Współczesność,3,NaN,NaN,google.com/maps,3,27.09.2026,1
5,136885205,Tadeusza Wendy,15,NaN,Centrum Medyczne,NaN,Centrum Medyczne,6,<NA>,2000,Współczesność,3,NaN,NaN,google.com/maps,2,27.09.2026,1

In [ ]:
data_gdynia.groupby("nfunc", as_index=False).agg(
    n_buildings=("addr_street", "size"),
    diff_streets=("addr_street", "nunique"),
    n_fill_adress=("addr_number", "count"),
)

   nfunc  n_buildings  diff_streets  n_fill_adress
0      1          876            45            569
1      2          150            28            148
2      3           55            13             54
3      4           17             6             17
4      5            4             2              4
5      6            2             2              2
6      8            1             1              1

6.

In [ ]:
def min_max(d):
    return d.max() - d.min()


f1 = data_gdynia.groupby("addr_street")["nfunc"].agg(min_max)
f2 = data_gdynia.groupby("addr_street")["nfunc"].apply(lambda d: d.max() - d.min())

In [12]:
assert f1.equals(f2)

7.

In [ ]:
n_on_street = data_gdynia.groupby("addr_street")["nfunc"].transform("size")
fin = n_on_street[n_on_street >= 10]
fin

id
1        16.0
2        16.0
4        16.0
9        16.0
11       16.0
        ...
1233    125.0
1234    125.0
1235     41.0
1237     41.0
1238    125.0
Name: nfunc, Length: 750, dtype: float64

In [ ]:
assert fin.min() >= 10

8.

In [ ]:
data_clean = data_gdynia.assign(
    ground_floor_function=lambda d: (
        d["ground_floor_function"].str.replace("_", " ").str.lower().str.split(",")
    )
)
data_long = data_gdynia.explode("ground_floor_function").assign(
    ground_floor_function=lambda d: d["ground_floor_function"].str.strip()
)

In [ ]:
data_long.groupby(["addr_street", "ground_floor_function"])[("osm_id")].agg(
    "count"
).reset_index().rename(columns={"osm_id": "count"})

,addr_street,ground_floor_function,count
0,10 Lutego,"Apteka,Żabka",1
1,10 Lutego,Bank,1
2,10 Lutego,"Bar,Handel Jubiler,Usługowy Zdrowie",1
3,10 Lutego,Centrum Handlowe,6
4,10 Lutego,Cukiernia,3
...,...,...,...
563,Świętojańska,"Żabka,Kosmetyczka,Okulista",1
564,Świętojańska,"Żabka,Restauracja",1
565,Żołnierzy I Armii Wojska Polskiego,Centrum Medyczne,1
566,Żołnierzy I Armii Wojska Polskiego,Cukiernia,1
567,Żołnierzy I Armii Wojska Polskiego,"Fryzjer,Restauracja",1

In [ ]:
top_func = (
    data_long.groupby(["addr_street", "ground_floor_function"])[("osm_id")]
    .agg("count")
    .reset_index()
    .sort_values(["addr_street", "osm_id"], ascending=[True, False])
    .rename(columns={"osm_id": "n"})
)
top_func_3 = top_func.groupby("addr_street").head(3)

In [ ]:
mask = top_func_3.groupby("addr_street").agg("size") > 3
assert mask.sum() == 0

In [ ]:
def sort_3(df, n=3):
    return df.sort_values("n", ascending=False, kind="stable")[:n]


counts = (
    data_long.groupby(["addr_street", "ground_floor_function"])["osm_id"]
    .agg("count")
    .reset_index()
    .rename(columns={"osm_id": "n"})
)
top_func_3b = counts.groupby("addr_street").apply(sort_3).reset_index(level=0)

In [20]:
assert top_func_3.equals(top_func_3b)

In [ ]:
data_clean = data_clean.assign(
    n_on_street=lambda d: d.groupby("addr_street")["osm_id"].transform("size")
)

9

In [ ]:
num_b_str = pd.cut(
    data_clean["n_on_street"],
    [0, 10, 50, 100, 200],
    labels=["small_str", "medium_str", "large_str", "main_str"],
).reset_index()
num_b_str.groupby("n_on_street").agg("size")

n_on_street
small_str     117
medium_str    456
large_str     139
main_str      125
dtype: int64

In [ ]:
mask = data_clean["addr_street"].isna()
assert (
    len(data_clean) == mask.sum() + num_b_str.groupby("n_on_street").agg("size").sum()
)

In [ ]:
data_clean = data_clean.assign(
    street_size=lambda d: pd.cut(
        d["n_on_street"],
        [0, 10, 50, 100, 200],
        labels=["small_str", "medium_str", "large_str", "main_str"],
    )
)
data_clean = data_clean.assign(is_multi=lambda d: d["nfunc"] > 1)

In [ ]:
print(f"no of multifunc buildings: {data_clean['is_multi'].sum()}")
print(
    f"share of multifunc buildings: {data_clean['is_multi'].sum() / len(data_clean):.2f}"
)

no of multifunc buildings: 229
share of multifunc buildings: 0.21

In [ ]:
data_clean.groupby("street_size")["is_multi"].agg(["count", "mean"])

             count      mean
street_size
small_str      117  0.247863
medium_str     456  0.160088
large_str      139  0.359712
main_str       125  0.608000

In [26]:
data_clean

,osm_id,addr_street,addr_number,ground_floor_group,ground_floor_function,upper_floor_group,upper_floor_function,number_of_storeys,is_mixed_use,build_year_est,...,condition,max_height,is_heritage,source,confidence,date_of_checking,nfunc,n_on_street,street_size,is_multi
id,,,,,,,,,,,,,,,,,,,,,
1,127184291,Świętego Piotra,8,NaN,[hotel],NaN,Hotel,7,<NA>,2000,...,3,NaN,NaN,google.com/maps,3,27.09.2026,1,16.0,medium_str,False
2,890729731,Świętego Piotra,6D,NaN,[mieszkaniowa wielorodzinna],NaN,Mieszkaniowa Wielorodzinna,5,<NA>,2020,...,3,NaN,NaN,google.com/maps,3,27.09.2026,1,16.0,medium_str,False
3,890292040,Węglowa,22,NaN,[centrum handlowe],NaN,Mieszkaniowa Wielorodzinna,17,<NA>,2020,...,3,NaN,NaN,google.com/maps,3,27.09.2026,1,1.0,small_str,False
4,890729732,Świętego Piotra,6,NaN,[mieszkaniowa wielorodzinna],NaN,Mieszkaniowa Wielorodzinna,17,<NA>,2020,...,3,NaN,NaN,google.com/maps,3,27.09.2026,1,16.0,medium_str,False
5,136885205,Tadeusza Wendy,15,NaN,[centrum medyczne],NaN,Centrum Medyczne,6,<NA>,2000,...,3,NaN,NaN,google.com/maps,2,27.09.2026,1,8.0,small_str,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1237,126180359,Władysława IV,61,NaN,"[laboratorium medyczne, piekarnia, kiosk]",NaN,Mieszkaniowa Wielorodzinna,7,<NA>,1940,...,3,NaN,NaN,google.com/maps,2,30.09.2026,3,41.0,medium_str,True
1238,126173503,Świętojańska,122,NaN,"[apteka, handel zdrowie]",NaN,Biurowa,6,<NA>,1930,...,2,NaN,NaN,google.com/maps,2,30.09.2026,2,125.0,main_str,True
1239,260676369,Aleja Marszałka Józefa Piłsudskiego,56,NaN,[mieszkaniowa wielorodzinna],NaN,Mieszkaniowa Wielorodzinna,7,<NA>,1930,...,2,NaN,NaN,google.com/maps,2,30.09.2026,1,3.0,small_str,False
1240,206252838,Aleja Marszałka Józefa Piłsudskiego,56,NaN,[restauracja],NaN,Mieszkaniowa Wielorodzinna,7,<NA>,1930,...,2,NaN,NaN,google.com/maps,2,30.09.2026,1,3.0,small_str,False
1241,125912675,Aleja Marszałka Józefa Piłsudskiego,52/54,NaN,[urząd miasta],NaN,Urząd Miasta,5,<NA>,1930,...,3,NaN,NaN,google.com/maps,3,30.09.2026,1,3.0,small_str,False